import type { LucideIcon } from 'lucide-react';
import { Skull, Flame, Zap, Sword, Ghost, Bug, Eye, Target, Radio, Disc3, Music2, Rocket, Crown, Anchor, Sun, Moon, Triangle, Hexagon, Circle, Square, Star, Heart, Sparkles, Hand, Cat, Dog, Fish, Bird, Leaf, Cloud } from 'lucide-react';

// Map icon names to Lucide components - shared between WorkbenchStage and export
export const iconMap: Record<string, LucideIcon> = {
  Skull,
  Flame,
  Zap,
  Sword,
  Ghost,
  Bug,
  Eye,
  Target,
  Radio,
  Disc: Disc3,
  Music: Music2,
  Rocket,
  Crown,
  Anchor,
  Sun,
  Moon,
  Triangle,
  Hexagon,
  Circle,
  Square,
  Star,
  Heart,
  Sparkles,
  Hand,
  Cat,
  Dog,
  Fish,
  Bird,
  Leaf,
  Cloud,
};
