import { MarketplaceDesign } from './marketplace';

/**
 * Seed data for the marketplace when no database designs exist.
 * These showcase what's possible and make the marketplace feel alive.
 */
export const marketplaceSeedDesigns: MarketplaceDesign[] = [
  {
    id: 'seed-001',
    user_id: 'community',
    title: 'Midnight Bloom',
    description: 'Dark floral design with neon petals blooming against a midnight background. Perfect for riders who love nature meets urban style.',
    file_url: '',
    thumbnail_url: null,
    price: 0,
    license_type: 'personal',
    tags: ['floral', 'neon', 'dark', 'nature'],
    category: 'edgy',
    views: 1247,
    downloads: 389,
    favorites: 156,
    featured_until: null,
    published: true,
    created_at: '2025-12-15T10:30:00Z',
    updated_at: '2025-12-15T10:30:00Z',
    designer: {
      email: 'neonartist@deckforge.com',
      bio: 'Digital artist specializing in dark aesthetic fingerboard graphics',
      verified: true,
    },
    is_favorited: false,
    is_purchased: false,
  },
  {
    id: 'seed-002',
    user_id: 'community',
    title: 'Tokyo Drift',
    description: 'Japanese-inspired street design with kanji-style typography and speed line accents. Built for the streets.',
    file_url: '',
    thumbnail_url: null,
    price: 1.99,
    license_type: 'commercial',
    tags: ['japanese', 'street', 'drift', 'speed'],
    category: 'street',
    views: 2103,
    downloads: 567,
    favorites: 234,
    featured_until: '2026-03-01T00:00:00Z',
    published: true,
    created_at: '2025-11-20T14:15:00Z',
    updated_at: '2025-11-20T14:15:00Z',
    designer: {
      email: 'tokyodesigns@deckforge.com',
      bio: 'JDM-inspired graphics for fingerboard culture',
      verified: true,
    },
    is_favorited: false,
    is_purchased: false,
  },
  {
    id: 'seed-003',
    user_id: 'community',
    title: 'Pastel Waves',
    description: 'Soft pastel gradient waves flowing across the deck. Smooth, calming, and stylish.',
    file_url: '',
    thumbnail_url: null,
    price: 0,
    license_type: 'personal',
    tags: ['pastel', 'waves', 'gradient', 'calm'],
    category: 'minimal',
    views: 891,
    downloads: 312,
    favorites: 178,
    featured_until: null,
    published: true,
    created_at: '2025-12-01T09:00:00Z',
    updated_at: '2025-12-01T09:00:00Z',
    designer: {
      email: 'wavecreative@deckforge.com',
      bio: 'Minimal design enthusiast',
      verified: false,
    },
    is_favorited: false,
    is_purchased: false,
  },
  {
    id: 'seed-004',
    user_id: 'community',
    title: 'Retro Cassette',
    description: 'Nostalgic 80s cassette tape design with mixtape label and magnetic tape details. Rewind the good times.',
    file_url: '',
    thumbnail_url: null,
    price: 2.49,
    license_type: 'commercial',
    tags: ['retro', 'cassette', '80s', 'music', 'nostalgia'],
    category: 'retro',
    views: 1556,
    downloads: 423,
    favorites: 201,
    featured_until: null,
    published: true,
    created_at: '2025-10-28T16:45:00Z',
    updated_at: '2025-10-28T16:45:00Z',
    designer: {
      email: 'retroripper@deckforge.com',
      bio: 'Taking it back to the 80s, one deck at a time',
      verified: true,
    },
    is_favorited: false,
    is_purchased: false,
  },
  {
    id: 'seed-005',
    user_id: 'community',
    title: 'Carbon Fiber Pro',
    description: 'Premium carbon fiber texture with precision-cut accent lines and competition-ready branding. Built for performance.',
    file_url: '',
    thumbnail_url: null,
    price: 3.99,
    license_type: 'unlimited',
    tags: ['carbon', 'pro', 'competition', 'premium', 'texture'],
    category: 'pro',
    views: 3210,
    downloads: 891,
    favorites: 445,
    featured_until: '2026-04-01T00:00:00Z',
    published: true,
    created_at: '2025-11-05T11:20:00Z',
    updated_at: '2025-11-05T11:20:00Z',
    designer: {
      email: 'prodecks@deckforge.com',
      bio: 'Competition-grade fingerboard graphics for serious riders',
      verified: true,
    },
    is_favorited: false,
    is_purchased: false,
  },
  {
    id: 'seed-006',
    user_id: 'community',
    title: 'Glitch Matrix',
    description: 'Digital glitch art with corrupted pixel patterns and matrix-style code rain. Error has never looked so good.',
    file_url: '',
    thumbnail_url: null,
    price: 1.49,
    license_type: 'personal',
    tags: ['glitch', 'digital', 'matrix', 'pixel', 'cyber'],
    category: 'edgy',
    views: 1823,
    downloads: 521,
    favorites: 267,
    featured_until: null,
    published: true,
    created_at: '2025-12-10T13:00:00Z',
    updated_at: '2025-12-10T13:00:00Z',
    designer: {
      email: 'glitchart@deckforge.com',
      bio: 'Breaking pixels since 1999',
      verified: false,
    },
    is_favorited: false,
    is_purchased: false,
  },
  {
    id: 'seed-007',
    user_id: 'community',
    title: 'Botanical Line Art',
    description: 'Delicate botanical illustrations with fine line work on a cream background. Nature meets minimalism.',
    file_url: '',
    thumbnail_url: null,
    price: 0,
    license_type: 'personal',
    tags: ['botanical', 'line-art', 'nature', 'minimal', 'illustration'],
    category: 'minimal',
    views: 756,
    downloads: 198,
    favorites: 134,
    featured_until: null,
    published: true,
    created_at: '2025-12-18T08:30:00Z',
    updated_at: '2025-12-18T08:30:00Z',
    designer: {
      email: 'linework@deckforge.com',
      bio: 'Illustrator and fingerboard enthusiast',
      verified: false,
    },
    is_favorited: false,
    is_purchased: false,
  },
  {
    id: 'seed-008',
    user_id: 'community',
    title: 'Acid Drip',
    description: 'Psychedelic acid-washed design with dripping colors and warped typography. Turn up the volume.',
    file_url: '',
    thumbnail_url: null,
    price: 1.99,
    license_type: 'commercial',
    tags: ['psychedelic', 'acid', 'drip', 'colorful', 'trippy'],
    category: 'retro',
    views: 2456,
    downloads: 678,
    favorites: 321,
    featured_until: null,
    published: true,
    created_at: '2025-11-12T15:00:00Z',
    updated_at: '2025-11-12T15:00:00Z',
    designer: {
      email: 'acidart@deckforge.com',
      bio: 'Psychedelic art for the fingerboard generation',
      verified: true,
    },
    is_favorited: false,
    is_purchased: false,
  },
];
